// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWUvsCsJD5pauXUmRldM1vBy0LaFAf0us',
    appId: '1:726391711741:web:9b03348bf3b10b2a88db94',
    messagingSenderId: '726391711741',
    projectId: 'to-do-list-e0b8b',
    authDomain: 'to-do-list-e0b8b.firebaseapp.com',
    storageBucket: 'to-do-list-e0b8b.firebasestorage.app',
    measurementId: 'G-4591PBMP0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBe0YDpnGYCuijyn2Sb8pl4HxjYl-4vu4',
    appId: '1:726391711741:android:ff86e4b052da315388db94',
    messagingSenderId: '726391711741',
    projectId: 'to-do-list-e0b8b',
    storageBucket: 'to-do-list-e0b8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwBjyo4YhmWxfKtnxh_3QfwV8UCqKCTxI',
    appId: '1:726391711741:ios:a3f80629f165720488db94',
    messagingSenderId: '726391711741',
    projectId: 'to-do-list-e0b8b',
    storageBucket: 'to-do-list-e0b8b.firebasestorage.app',
    iosBundleId: 'com.example.baseTodolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWUvsCsJD5pauXUmRldM1vBy0LaFAf0us',
    appId: '1:726391711741:web:6cec04295f09072d88db94',
    messagingSenderId: '726391711741',
    projectId: 'to-do-list-e0b8b',
    authDomain: 'to-do-list-e0b8b.firebaseapp.com',
    storageBucket: 'to-do-list-e0b8b.firebasestorage.app',
    measurementId: 'G-7XHZ9CTGHD',
  );
}
